apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-graphql-ingress
  namespace: filmapi
  labels:
    app.kubernetes.io/name: api-graphql
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: filmapi-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: graphql.tp.k0li.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-graphql-service
                port:
                  number: 8001
  tls:
    - hosts:
        - graphql.tp.k0li.fr
      secretName: api-graphql-tls
