apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: graphql-api

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  # DÃ©commenter si vous utilisez un Ingress
  # - ingress.yaml

commonLabels:
  app: graphql-api
  environment: production

# Permet de personnaliser l'image facilement
images:
  - name: maxxa/py_graphql
    newTag: latest
