apiVersion: v1
kind: Secret
metadata:
  name: api-graphql-secret
  namespace: filmapi
  labels:
    app.kubernetes.io/name: api-graphql
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: filmapi-stack
type: Opaque
stringData:
  # Clé API LLM (si nécessaire)
  # En production, utilisez des outils comme Sealed Secrets ou External Secrets
  LLM_CHAT_API_KEY: "not-needed"
