apiVersion: v1
kind: Service
metadata:
  name: graphql-api-service
  labels:
    app: graphql-api
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: graphql-api
---
# Optionnel: Service NodePort pour accès externe en développement
# apiVersion: v1
# kind: Service
# metadata:
#   name: graphql-api-nodeport
#   labels:
#     app: graphql-api
# spec:
#   type: NodePort
#   ports:
#     - port: 8002
#       targetPort: 8002
#       nodePort: 30002
#       protocol: TCP
#       name: http
#   selector:
#     app: graphql-api
